### ISSUE TITLE
all tooltips are covered under charts

### ISSUE THREAD

**Issue by PitPaul** [influxdata/chronograf#1383]
![tooltips-hidden](https://cloud.githubusercontent.com/assets/26178409/25661156/a8bbe42a-300f-11e7-92f5-a74656112d7c.png)

**Comment by nhaugo** [comment]
Hi @PitPaul can you tell me what version you are running. This should be fixed. If you are on beta-10 already try a force reload.

**Comment by PitPaul** [comment]
Hi
This is my version chronograf_1.2.0~beta10_amd64.deb on Ubuntu 16.04
Force reload don’t help on Firefox, Chrome and android web-kit.

**Comment by hasselrot** [comment]
@nhaugo @PitPaul I was just going to report this as well.
Both Chrome and Safari experience this.
Running Chronograf 1.2.0~beta10 (git: ae27d5e6fd847b689a833112f6e701d25805f83c)

**Comment by AlbinOS** [comment]
Hi,

I had the issue before (beta7 I think) and it was fixed but I have it again after installing beta10.

Regards and keep the great work,
Albin.

**Comment by nhaugo** [comment]
Sorry about the late reply @PitPaul or @hasselrot is this issue still present int 1.3.x I have not seen or heard of it for a while?

**Comment by hasselrot** [comment]
Hi!

I have a couple of different versions running at the moment. The only place where this is still an issue is on 1.2.0-beta10.

It seems to be solved in 1.3.x!

**Comment by PitPaul** [comment]
Yep, agree. In previous version creation order was important.
Now works either  custom dashboard  or  build-in ones
