### ISSUE TITLE
range(start: , end: ) & date picker not working 

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/chronograf#4855]
Using: Chronograf 1.7.3, Influxdb 1.7.1, Chrome 

Expection one: 
This query to yield results in the correct time range
```
from(bucket: "telegraf") 
|> range(start:2018-11-29T01:00:00Z, stop:2018-11-29T03:00:00Z) 
|> filter(fn: (r) => r._measurement == "cpu" and r._field == "usage_system")
  ``` 
CLI yields correct results: 
<img width="1604" alt="screen shot 2018-11-29 at 2 37 42 pm" src="https://user-images.githubusercontent.com/30506042/49252299-44ae4000-f3e9-11e8-90b8-9778d570234d.png">

Flux builder in Chronograf does not. Notice how the field values are the same, but the timestamps have been changed. 
<img width="1389" alt="screen shot 2018-11-29 at 2 38 31 pm" src="https://user-images.githubusercontent.com/30506042/49252330-5859a680-f3e9-11e8-9645-ad50e5421e7b.png">

Expectation two:
Date picker end time isn't responsive. It defaults to the last timestamp. 
When I try to query 10min of data from yesterday, instead I get: 
<img width="1442" alt="screen shot 2018-11-29 at 3 25 40 pm" src="https://user-images.githubusercontent.com/30506042/49253102-732d1a80-f3eb-11e8-95cb-b0b6ca09343e.png">

**Comment by phaethon** [comment]
I have, also, experienced issues with date end picker. When I save to dashboard it works from dashboard view. At least for me it was unique to the Explore view.

**Comment by russorat** [comment]
i believe this was fixed in 1.7.11. Please check and reopen if needed.

**Comment by ajspera** [comment]
I am still seeing this issue on v1.7.14 with InfluxQL. Similarly date range works on dashboard ranges, but does not on explorer. I have not tested with Flux since we don't use it, but the InfluxQL comes out functionally the same as this issue's Flux error with `WHERE time > :dashboardTime: `. I'm not even sure what the end time variable is called to punch it in manually.
