### ISSUE TITLE
Missing charts

### ISSUE THREAD

**Issue by jimaek** [influxdata/chronograf#774]
Chronograf 1.1.0~beta6-1 
CentOS 7.3.1611 x64
telegraf config https://gist.githubusercontent.com/jimaek/1c7c55ea4a416e9d91a6c83c9774d5e4/raw/d8c601718ad612ace6e56e66cce7e1f1f25835b3/gistfile1.conf

![charts](https://cloud.githubusercontent.com/assets/1834071/21954951/851f0dd0-da60-11e6-9003-f7f49ee96438.png)

1. Why there is a hole in the charts? It looks bad like the screen is missing 2 charts
2. I dont see the following charts: diskio, net, procstat

**Comment by goller** [comment]
@jimaek Thanks for writing in!  

> 1. Why there is a hole in the charts? It looks bad like the screen is missing 2 charts
I'll work on reproducing this.  I have an idea what it is, but, I'll take your configuration and make sure it doesn't have those ugly blanks.

> 2. I dont see the following charts: diskio, net, procstat

* Well... somehow I didn't add `net` in; only `netstat`.  Ug!  I'll add the canned layout for `net` ASAP.
* Exactly the same problem with `diskio`; I added `disk`.  Again, I'll add `diskio` right now.
* ... and the same with `procstat`; I added `processes`.  I'll add `procstat` as well.

I added feature requests #775, #776 and #777 for these.  If you have input about what queries would be nice to have by default for those telegraf plugins, I'd love the input!

**Comment by jimaek** [comment]
Great thank you!
I'l think about the inputs and let you know. 

Also I have an other question. The values in the charts dont always make sense. For example the following is confusing:
![chrome_2017-01-14_18-36-00](https://cloud.githubusercontent.com/assets/1834071/21956772/5620250a-da88-11e6-9566-0345de9b197d.png)
3billion bytes is not very clear. Why not 3GB? or at least use MB.

I've seen this kind of of problem in a lot of charts. In some the problem is even worse because I dont know what its supposed to show. For example:
![influx](https://cloud.githubusercontent.com/assets/1834071/21956789/a868f81e-da88-11e6-8153-b5a283ad9068.png)

What does that even show? Its says duration but the value is in millions?

**Comment by goller** [comment]
@jimaek Good point! No y-axis labels trigger me.  We added support for y-labels but have not updated all of our layouts yet (actually, looks like we have not updated any).

I've added another issue, #778, to add all the labels.

**Comment by jimaek** [comment]
@goller I asked in the google group but nobody answered me. Maybe you could help?  I dont understand how I can remove old hosts that no longer send any data.

**Comment by goller** [comment]
Hey @jimaek, no problem.  We've been having our company get-together this week.

So, yup, influxql does support deleting data that way: https://docs.influxdata.com/influxdb/v1.1/query_language/spec/#delete

Basically, you'll do something like this:
`DELETE FROM "telegraf" WHERE host='testhost'`

**Comment by jimaek** [comment]
Any plans to add this as a chronograf button?

**Comment by nhaugo** [comment]
@jimaek added #795. Thanks for all the feedback, this particular issue seems to be more of a discussion that spawned a number of features/bugs. I'm going to close it since I think we have everything in different issues now. Let me know if there is something else we are missing.

**Comment by goller** [comment]
@jimaek @timraymond and I fixed the gaps in the layouts and #812.

**Comment by jimaek** [comment]
@goller I updated to 1.2.0~beta1-1 today but I still see the gap problem. Do I need to do anything else ?


![chrome_2017-01-31_13-47-10](https://cloud.githubusercontent.com/assets/1834071/22465446/0c8becbc-e7bc-11e6-975c-70a9893b208f.png)

**Comment by goller** [comment]
@jimaek bummer, there must be something else lurking.  @timraymond perhaps we could carve out some time this afternoon and use @jimaek telegraf config?

**Comment by jimaek** [comment]
Is it possible to get this gap if a configured telegraf input is not sending any data?

**Comment by goller** [comment]
@jimaek Ah! I'll try that out and see if I can reproduce.  Good idea.

**Comment by goller** [comment]
@jimaek Hey there, @cryptoquick and I spent the afternoon trying to reproduce this with you telegraf configuration.  Sadly, we weren't able to do it.

So, we have a wild hope... would you force-reload your webpage? It's probably not that, but, maybe?

In any case, we created case #836 that involves reporting front-end state to us so we can do more proper debugging.

**Comment by jimaek** [comment]
Tried hard-refresh, didnt help :)

The positions are also different on different types of nodes.
non-web nodes: 
https://dl.dropboxusercontent.com/u/13590841/ShareX/2017/01/chrome_2017-01-31_23-49-48.png

web-nodes look good:
https://dl.dropboxusercontent.com/u/13590841/ShareX/2017/01/chrome_2017-01-31_23-50-50.png

influx db:
https://dl.dropboxusercontent.com/u/13590841/ShareX/2017/01/chrome_2017-01-31_23-51-19.png

Its possible that some telegraf metrics even though configured to work never reported any data. But since chronograf doesnt even show some metrics its not that easy to debug. If you tested it and it wasnt that then I have no idea.

**Comment by goller** [comment]
Thanks for the screen caps... yeah at this point we'll spend some time to work on #836 so we can get some of the internal front-end state back to us.

**Comment by jaredscheib** [comment]
@121watts This seems unresolved -- why close it?
